version: '3'

services:
  # Red.s
  redis:
    image: redis:5.0
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  # Django Zappa app
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - YOUR_VAR=testvar
#    volumes:
#      - ./src/:/usr/src/app/

volumes:
  redis:
